window.LOVE_ALBUM_CONFIG = {
  sitePassword: "1314",
  supabaseUrl: "https://xdlrxqelqszqldblygma.supabase.co",
  supabaseAnonKey: "sb_publishable_8DTggSrA_sH4bXzBNbFl2A_QcJKHOG-",
  bucketName: "love-photos",
  tableName: "memories",
  checkinTableName: "daily_checkins",
  chatMessageTableName: "couple_chat_messages",
  statusTableName: "couple_status_cards",
  riddleTableName: "couple_riddles",
  questionRoundTableName: "couple_question_rounds",
  drawRoundTableName: "couple_draw_rounds",
  hugTableName: "couple_hugs",
  lampTableName: "couple_goodnight_lamps",
  scoreTableName: "couple_miss_scores",
  syncQuestionTableName: "couple_sync_questions",
  capsuleTableName: "couple_capsules",
  gardenWaterTableName: "couple_garden_watering",
  babyFeedTableName: "couple_baby_feeds"
};
